exports.sampleData = [
  {
    property_name: "Apartment A",
    property_value: 250000,
    property_size: "1200 sq ft",
    lead_creation_date: "2023-12-15",
    status: "pre-login",
    customer_name: "John Smith",
    customer_cibil_score: 720,
    customer_employment_details: "salaried",
    monthly_income: 5000,
    monthly_obligations: 2000,
  },
  {
    property_name: "House B",
    property_value: 300000,
    property_size: "1500 sq ft",
    lead_creation_date: "2024-01-05",
    status: "logged-in",
    customer_name: "Emily Johnson",
    customer_cibil_score: 680,
    customer_employment_details: "non-salaried",
    monthly_income: 4500,
    monthly_obligations: 1500,
  },
  {
    property_name: "Condo C",
    property_value: 200000,
    property_size: "1000 sq ft",
    lead_creation_date: "2024-02-20",
    status: "disbursed",
    customer_name: "Michael Brown",
    customer_cibil_score: 700,
    customer_employment_details: "salaried",
    monthly_income: 6000,
    monthly_obligations: 2500,
  },
  {
    property_name: "Villa D",
    property_value: 500000,
    property_size: "2500 sq ft",
    lead_creation_date: "2024-01-10",
    status: "pre-login",
    customer_name: "Sophia Wilson",
    customer_cibil_score: 740,
    customer_employment_details: "non-salaried",
    monthly_income: 7000,
    monthly_obligations: 2000,
  },
  {
    property_name: "Townhouse E",
    property_value: 280000,
    property_size: "1300 sq ft",
    lead_creation_date: "2024-03-02",
    status: "logged-in",
    customer_name: "Daniel Martinez",
    customer_cibil_score: 710,
    customer_employment_details: "salaried",
    monthly_income: 5500,
    monthly_obligations: 1800,
  },
  {
    property_name: "Apartment F",
    property_value: 320000,
    property_size: "1600 sq ft",
    lead_creation_date: "2024-02-18",
    status: "disbursed",
    customer_name: "Olivia Garcia",
    customer_cibil_score: 690,
    customer_employment_details: "salaried",
    monthly_income: 6200,
    monthly_obligations: 2400,
  },
  {
    property_name: "House G",
    property_value: 350000,
    property_size: "1700 sq ft",
    lead_creation_date: "2024-03-10",
    status: "pre-login",
    customer_name: "William Anderson",
    customer_cibil_score: 730,
    customer_employment_details: "non-salaried",
    monthly_income: 5800,
    monthly_obligations: 1900,
  },
  {
    property_name: "Condo H",
    property_value: 180000,
    property_size: "900 sq ft",
    lead_creation_date: "2024-02-05",
    status: "logged-in",
    customer_name: "Ava Taylor",
    customer_cibil_score: 710,
    customer_employment_details: "salaried",
    monthly_income: 5300,
    monthly_obligations: 1700,
  },
  {
    property_name: "Villa I",
    property_value: 480000,
    property_size: "2400 sq ft",
    lead_creation_date: "2024-03-18",
    status: "disbursed",
    customer_name: "James Martinez",
    customer_cibil_score: 720,
    customer_employment_details: "salaried",
    monthly_income: 6500,
    monthly_obligations: 2300,
  },
  {
    property_name: "Townhouse J",
    property_value: 260000,
    property_size: "1250 sq ft",
    lead_creation_date: "2024-01-25",
    status: "pre-login",
    customer_name: "Mia Davis",
    customer_cibil_score: 700,
    customer_employment_details: "non-salaried",
    monthly_income: 5200,
    monthly_obligations: 1600,
  },
  {
    property_name: "Apartment K",
    property_value: 340000,
    property_size: "1700 sq ft",
    lead_creation_date: "2024-03-05",
    status: "logged-in",
    customer_name: "Liam Wilson",
    customer_cibil_score: 710,
    customer_employment_details: "salaried",
    monthly_income: 5900,
    monthly_obligations: 2000,
  },
  {
    property_name: "House L",
    property_value: 380000,
    property_size: "1900 sq ft",
    lead_creation_date: "2024-02-10",
    status: "disbursed",
    customer_name: "Amelia Brown",
    customer_cibil_score: 720,
    customer_employment_details: "salaried",
    monthly_income: 6400,
    monthly_obligations: 2200,
  },
  {
    property_name: "Condo M",
    property_value: 220000,
    property_size: "1100 sq ft",
    lead_creation_date: "2024-03-12",
    status: "pre-login",
    customer_name: "Ethan Garcia",
    customer_cibil_score: 690,
    customer_employment_details: "non-salaried",
    monthly_income: 5100,
    monthly_obligations: 1500,
  },
  {
    property_name: "Villa N",
    property_value: 520000,
    property_size: "2600 sq ft",
    lead_creation_date: "2024-01-15",
    status: "logged-in",
    customer_name: "Avery Rodriguez",
    customer_cibil_score: 730,
    customer_employment_details: "salaried",
    monthly_income: 6700,
    monthly_obligations: 2100,
  },
];
